#!/bin/sh

# intall nymea-networkmanager
systemctl cat nymea-networkmanager > /dev/null 2>&1
if [ $? != 0 ]; then
  echo "deb http://repository.nymea.io buster rpi" | sudo tee /etc/apt/sources.list.d/nymea.list
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key A1A19ED6
fi

# install raspotify if it's not installed
systemctl cat raspotify > /dev/null 2>&1
if [ $? != 0 ]; then
  curl -sL https://dtcooper.github.io/raspotify/install.sh | sh
fi

# build and install or upgrade shairport-sync
shairport-sync -V | grep '3.3.8rc2-libdaemon-OpenSSL-Avahi-ALSA-pa-soxr-metadata-sysconfdir:/etc' > /dev/null 2>&1
if [ $? != 0 ]; then
  cd /tmp || exit
  git clone https://github.com/mikebrady/shairport-sync.git
  # build with required options
  cd shairport-sync || exit
  autoreconf -i -f
  ./configure --sysconfdir=/etc --with-alsa --with-pa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd --with-configfiles --with-libdaemon
  make
  make install
  cd /tmp || exit
  rm -r shairport-sync
fi

# install bt_speaker if it's missing
if [ ! -f "/opt/bt-speaker/bt_speaker.service" ]; then
  curl -sL https://raw.githubusercontent.com/lukasjapan/bt-speaker/master/install.sh | sh
fi

# install python dependencies
python -c "import shairportmetadatareader,adafruit_bitbangio,rpilcdmenu,adafruit_mcp3xxx" > /dev/null 2>&1
if [ $? != 0 ]; then
  pip3 install git+https://github.com/domb84/rpi-lcd-menu
  pip3 install git+https://github.com/htruong/shairport-metadatareader-python
  pip3 install adafruit-circuitpython-mcp3xxx
  pip3 install adafruit-circuitpython-bitbangio
fi
